### PR TITLE
Add 'migrate' target to Makefile and improvment in README.md

### PR DESCRIPTION
**Pull request by sevdimali**
## Description of changes
- Minor improvement in the `README.md`

## How to test?
-

### CODE REVIEW

**Comment by ShahriyarR** [comment]
Thanks for the PR.

The migrations were intentionally abandoned. As we have no admin panel or database tables to work with, there is no need for built-in table migrations.
Only while running the tests, the Django TestCase will create test tables, which should be dropped after test completion.

**Comment by sevdimali** [comment]
> Thanks for the PR.
> 
> The migrations were intentionally abandoned. As we have no admin panel or database tables to work with, there is no need for built-in table migrations. Only while running the tests, the Django TestCase will create test tables, which should be dropped after test completion.

@ShahriyarR 
image

**Comment by ShahriyarR** [comment]
@sevdimali 
Interesting.

For local testing and to make it close to production setup I use the following commands:

First fire up the gunicorn:

```
make run
```

Second enable https over ngrok:

```
ngrok HTTP 8000
```

And that's it. Basically, it should work locally as well.
I am not sure why it tries to access the Django session.

**Comment by sevdimali** [comment]
I didn't get the error while browsing in incognito mode.
I think the problem is, I accessed the local development server from the `HTTP` and in regular browsing mode, the session cookie will not be sent by the browser(`SESSION_COOKIE_SECURE = True`). As a result, Django tries to create it in the database and throws the `no such table: django_session` error.
I am not 100% sure about it 😬

**Review by ShahriyarR — APPROVED** [review]

**Pull request merged**
